// dicionario.js

const DICIONARIO = {
    "sagaz": "Pessoa que tem grande capacidade de compreender as coisas; perspicaz, esperto.",
    "negro": "Cor que representa a ausência de luz; indivíduo de pele escura.",
    "amigo": "Aquele que demonstra amizade; companheiro, aliado.",
    "exito": "Resultado bem-sucedido de qualquer empreendimento; sucesso.",
    "mexer": "Mover ou deslocar algo; tocar, manusear.",
    "termo": "Palavra ou expressão; limite, fim.",
    "nobre": "Que possui título de nobreza; de caráter elevado, digno.",
    "senso": "Capacidade de julgar ou apreciar; bom juízo, discernimento.",
    "afeto": "Sentimento de carinho ou afeição por alguém; amizade, amor.",
    "plena": "Que está completamente cheia; completa, inteira.",
    "etica": "Parte da filosofia que estuda os valores morais e os princípios ideais da conduta humana.",
    "sutil": "Que é muito fino ou delicado; que não se percebe facilmente.",
    "vigor": "Força física ou moral; energia, robustez.",
    "fazer": "Realizar uma ação ou tarefa; criar, produzir.",
    "ideia": "Representação mental de algo concreto ou abstrato; pensamento.",
    "poder": "Ter a capacidade ou a faculdade de fazer algo; autoridade, soberania.",
    "moral": "Conjunto de regras de conduta consideradas como válidas; lição.",
    "honra": "Sentimento de dignidade pessoal; probidade, respeitabilidade.",
    "justo": "Que age de acordo com a justiça; imparcial, íntegro.",
    "muito": "Em grande quantidade ou intensidade; bastante.",
    "anexo": "Aquilo que se junta a algo principal; adjunto.",
    "fosse": "Forma do verbo ser ou ir; se eu fosse, se ele fosse.",
    "sonho": "Sequência de pensamentos e imagens durante o sono; desejo, fantasia.",
    "tange": "Diz respeito a; refere-se, concerne.",
    "lapso": "Erro involuntário; pequeno espaço de tempo.",
    "expor": "Apresentar, mostrar; revelar, explicar.",
    "haver": "Existir; ter, possuir; acontecer.",
    "dengo": "Demonstração de afeto, carinho ou manha.",
    "casal": "Par de pessoas ligadas por laço sentimental ou matrimonial.",
    "saber": "Ter conhecimento de algo; entender.",
    "pesar": "Avaliar o peso de algo; causar tristeza ou mágoa.",
    "graça": "Qualidade que atrai e encanta; favor, benefício.",
    "certo": "Que está correto, exato; algo definido.",
    "criar": "Dar existência a algo; formar, gerar.",
    "impor": "Obrigar, forçar; colocar em posição de destaque.",
    "falar": "Expressar-se por meio de palavras; comunicar.",
    "pedir": "Solicitar algo a alguém; rogar, implorar.",
    "prole": "Conjunto dos filhos de uma pessoa ou de um casal.",
    "dever": "Obrigação moral ou legal; ter de pagar uma dívida.",
    "tempo": "Período contínuo no qual os eventos se sucedem.",
    "corja": "Grupo de pessoas desonestas ou de má reputação; súcia.",
    "feliz": "Que sente alegria, contentamento; que tem sorte.",
    "mundo": "O planeta Terra; conjunto de tudo o que existe.",
    "verbo": "Palavra que indica ação, estado ou fenômeno da natureza.",
    "apice": "O ponto mais alto ou extremo de algo; auge.",
    "forte": "Que tem força física ou grande resistência; robusto.",
    "lugar": "Espaço ocupado ou que pode ser ocupado; localidade.",
    "chuva": "Precipitação de água em gotas das nuvens.",
    "sorte": "Força desconhecida que determina os acontecimentos; destino, acaso feliz.",
    "genio": "Pessoa com extraordinária capacidade intelectual ou criativa.",
    "bravo": "Corajoso, valente; irritado, zangado.",
    "festa": "Reunião de pessoas para celebrar algo; comemoração.",
    "abrir": "Descerrar, destampar, desvendar.",
    "achar": "Encontrar algo ou alguém; julgar, considerar.",
    "ajuda": "Ato de auxiliar; socorro, assistência.",
    "andar": "Mover-se, caminhar; funcionar.",
    "antes": "Em tempo ou lugar anterior; previamente.",
    "apelo": "Pedido de ajuda ou socorro; recurso.",
    "apoio": "Ato de apoiar; base, sustentação.",
    "arroz": "Planta e grão de cereal muito consumido.",
    "arvor": "Forma antiga de 'árvore'.",
    "assaz": "Bastante, muito; em grau elevado.",
    "assim": "Deste modo, desta maneira.",
    "astro": "Corpo celeste (estrela, planeta, cometa).",
    "atomo": "A menor partícula de um elemento químico.",
    "atras": "Na parte posterior; em tempo passado.",
    "atual": "Que existe ou acontece no tempo presente.",
    "audio": "Relativo à audição ou ao som.",
    "autor": "Aquele que cria uma obra literária, artística ou científica.",
    "avisar": "Informar, comunicar, prevenir.",
    "axial": "Relativo a um eixo.",
    "bahia": "Grande reentrância de mar na costa.",
    "banal": "Comum, trivial, sem originalidade.",
    "banca": "Mesa para exposição de mercadorias; conjunto de examinadores.",
    "banho": "Ato de lavar o corpo; imersão em água.",
    "barco": "Pequena embarcação a remo, vela ou motor.",
    "bater": "Dar pancadas em algo ou alguém; colidir.",
    "beber": "Ingerir líquidos, especialmente água.",
    "beijo": "Toque dos lábios em alguém ou algo como sinal de afeto.",
    "belo": "Que tem beleza; bonito, formoso.",
    "bolsa": "Saco ou carteira para transportar objetos; auxílio financeiro.",
    "brasa": "Carvão ou lenha em estado de combustão, sem chama.",
    "breve": "De curta duração; rápido, conciso.",
    "brisa": "Vento leve e fresco, geralmente agradável.",
    "busca": "Ato de procurar algo ou alguém.",
    "cabelo": "Conjunto de pelos que crescem na cabeça.",
    "calma": "Ausência de agitação; tranquilidade, sossego.",
    "campo": "Área de terra aberta; zona rural.",
    "canil": "Lugar destinado à criação e alojamento de cães.",
    "canto": "Ato de cantar; ângulo, esquina.",
    "carro": "Veículo motorizado de quatro rodas para transporte.",
    "carta": "Mensagem escrita enviada a alguém; papel de baralho.",
    "casto": "Que se abstém de prazeres carnais; puro, inocente.",
    "causa": "Aquilo que faz com que algo exista ou aconteça; motivo.",
    "ceder": "Desistir de algo; transferir, dar.",
    "chefe": "Pessoa que tem o cargo de liderança; patrão.",
    "cheio": "Que contém tudo o que pode; repleto.",
    "choro": "Ato de chorar; emissão de lágrimas e soluços.",
    "chulo": "Grosseiro, de baixo nível; vulgar.",
    "ciclo": "Série de fenômenos que se repetem numa ordem determinada.",
    "cinco": "Numeral cardinal correspondente a 5.",
    "cisma": "Preocupação insistente; separação em uma organização.",
    "civil": "Relativo ao cidadão; não militar nem religioso.",
    "claro": "Que tem luz; evidente, compreensível.",
    "clima": "Condições atmosféricas de uma região.",
    "coeso": "Que tem ligação, harmonia; unido.",
    "coisa": "Objeto inanimado; qualquer entidade.",
    "comer": "Ingerir alimentos; mastigar e deglutir.",
    "conta": "Ato de contar; fatura, débito.",
    "conto": "Narrativa curta; história fictícia.",
    "corpo": "Estrutura física de um ser vivo.",
    "correr": "Mover-se rapidamente; fluir.",
    "costa": "Litoral; parte de trás do corpo.",
    "crime": "Ato que viola a lei penal; delito grave.",
    "crise": "Momento de dificuldade ou instabilidade.",
    "cruel": "Que gosta de fazer o mal; desumano.",
    "culto": "Homenagem religiosa; pessoa instruída.",
    "cunho": "Impressão deixada em metal; caráter, marca.",
    "curar": "Restituir a saúde; remediar.",
    "curso": "Percurso, direção; série de aulas.",
    "custo": "Valor monetário de produção ou aquisição.",
    "dança": "Arte de mover o corpo em ritmo.",
    "dados": "Informações; plural de 'dado', objeto de jogo.",
    "digno": "Que merece respeito; honrado.",
    "dizer": "Expressar por palavras; afirmar.",
    "doce": "Que tem sabor de açúcar; agradável.",
    "dogma": "Ponto fundamental de uma doutrina religiosa, tido como verdade absoluta.",
    "drama": "Peça teatral; acontecimento trágico.",
    "duelo": "Combate entre duas pessoas com armas.",
    "duzia": "Conjunto de doze unidades.",
    "ecoar": "Repetir um som; ressoar.",
    "enfim": "Finalmente, em conclusão.",
    "entao": "Nesse caso, portanto; naquele tempo.",
    "errar": "Cometer um erro; não acertar.",
    "espir": "Exalar, emitir de si.",
    "estar": "Achar-se em determinado lugar ou situação.",
    "etapa": "Fase de um processo ou percurso.",
    "exato": "Que é preciso, correto.",
    "facil": "Que não exige grande esforço.",
    "falha": "Defeito, imperfeição; erro.",
    "falso": "Que não é verdadeiro; enganoso.",
    "farol": "Torre com luz para orientar navios.",
    "farto": "Em grande quantidade; abundante.",
    "fatal": "Que causa a morte; inevitável.",
    "favor": "Ato de ajudar; benefício.",
    "fauna": "Conjunto de animais de uma região.",
    "feixe": "Conjunto de objetos amarrados; molho.",
    "filho": "Descendente masculino.",
    "filme": "Obra cinematográfica; película.",
    "final": "Parte que conclui algo; término.",
    "fluir": "Correr como um líquido; manar.",
    "folga": "Período de descanso; lazer.",
    "forma": "Aspecto exterior dos objetos; molde.",
    "forno": "Aparelho para assar ou aquecer.",
    "fraco": "Que tem pouca força; frágil.",
    "frase": "Enunciado com sentido completo.",
    "freio": "Dispositivo para parar um veículo.",
    "futil": "Que tem pouca ou nenhuma importância.",
    "ganho": "Aquilo que se ganha; lucro, vantagem.",
    "garfo": "Utensílio de mesa com dentes.",
    "gerar": "Produzir, dar origem a.",
    "gesto": "Movimento do corpo, especialmente das mãos.",
    "glosa": "Comentário, explicação; anotação.",
    "gosto": "Sentido do paladar; preferência.",
    "grato": "Agradecido; que sente gratidão.",
    "grave": "Sério, importante; som de baixa frequência.",
    "grito": "Voz emitida com força; clamor.",
    "grupo": "Conjunto de pessoas ou coisas.",
    "heroi": "Pessoa admirada por seus feitos e coragem.",
    "hiato": "Encontro de duas vogais em sílabas diferentes.",
    "hobby": "Atividade de lazer praticada por prazer.",
    "homem": "Ser humano do sexo masculino.",
    "hoste": "Exército; multidão de inimigos.",
    "humor": "Estado de ânimo; capacidade de fazer rir.",
    "icone": "Símbolo ou imagem que representa algo.",
    "idolo": "Pessoa ou objeto muito admirado ou venerado.",
    "igual": "Que é da mesma natureza ou quantidade.",
    "impar": "Que não é divisível por dois.",
    "imune": "Que não pode ser atacado por certa doença.",
    "indio": "Nativo ou habitante original da América.",
    "inerte": "Que não se move por si só; inativo.",
    "inicio": "O começo de algo; princípio.",
    "istmo": "Faixa de terra estreita entre dois mares.",
    "jante": "Aro metálico da roda de um veículo.",
    "jarda": "Unidade de medida de comprimento (91,44 cm).",
    "jarro": "Vaso com asa para líquidos.",
    "jovem": "Pessoa que está na juventude.",
    "jogar": "Praticar um jogo ou esporte; arremessar.",
    "juizo": "Faculdade de julgar; bom senso.",
    "julgar": "Formar um juízo sobre algo; sentenciar.",
    "junto": "Unido, próximo, perto.",
    "labor": "Trabalho, esforço, labuta.",
    "lagoa": "Corpo de água doce, menor que um lago.",
    "laico": "Que não pertence ao clero; não religioso.",
    "lapis": "Instrumento para escrever ou desenhar.",
    "largo": "Que tem grande largura; amplo.",
    "laser": "Dispositivo que emite luz concentrada.",
    "laudo": "Parecer técnico de um especialista.",
    "lazer": "Tempo livre para descanso ou diversão.",
    "legua": "Antiga medida de distância (cerca de 6 km).",
    "leigo": "Que não é especialista em certo assunto.",
    "leito": "Cama; fundo de um rio.",
    "lento": "Que se move devagar; vagaroso.",
    "letra": "Sinal gráfico de um alfabeto.",
    "levar": "Transportar de um lugar para outro.",
    "livro": "Conjunto de folhas impressas e encadernadas.",
    "louco": "Que perdeu a razão; insano.",
    "louro": "Cor de cabelo entre o amarelo e o castanho.",
    "lousa": "Quadro negro para escrever com giz.",
    "lutar": "Combater; esforçar-se para conseguir algo.",
    "macio": "Que é agradável ao tato; suave.",
    "maior": "De tamanho ou quantidade superior.",
    "malha": "Tecido de fios entrelaçados; rede.",
    "mamãe": "Forma carinhosa de se referir à mãe.",
    "manga": "Fruta tropical; parte da roupa que cobre o braço.",
    "manha": "Período do dia que vai do amanhecer ao meio-dia.",
    "manto": "Peça de vestuário que se usa sobre os ombros.",
    "marco": "Ponto de referência; evento importante.",
    "maria": "Nome próprio feminino comum.",
    "matiz": "Variação de uma cor; tonalidade.",
    "meigo": "Delicado, terno, afetuoso.",
    "meio": "Metade; centro; maneira.",
    "mente": "Faculdade de pensar, raciocinar e sentir.",
    "mesmo": "Igual, idêntico; próprio.",
    "metro": "Unidade de medida de comprimento.",
    "mimos": "Carinhos, afagos; presentes.",
    "moeda": "Peça metálica usada como dinheiro.",
    "moita": "Conjunto de pequenas árvores ou arbustos.",
    "molde": "Peça que dá forma a algo.",
    "molho": "Líquido culinário para temperar; feixe.",
    "monte": "Grande elevação de terra; montanha pequena.",
    "morte": "Fim da vida; cessação das funções vitais.",
    "motor": "Máquina que produz movimento.",
    "mover": "Mudar de lugar; deslocar.",
    "multa": "Penalidade em dinheiro por uma infração.",
    "musgo": "Planta pequena que cresce em lugares úmidos.",
    "nadar": "Mover-se na água usando o corpo.",
    "nasal": "Relativo ao nariz.",
    "nascer": "Vir ao mundo; começar a existir.",
    "natal": "Festa cristã que celebra o nascimento de Jesus.",
    "navio": "Embarcação de grande porte.",
    "nicho": "Cavidade em um muro; segmento de mercado.",
    "ninfa": "Divindade mitológica feminina da natureza.",
    "nivel": "Altura ou grau em uma escala; plano.",
    "noite": "Período do dia sem a luz do sol.",
    "nosso": "Pronome possessivo da primeira pessoa do plural.",
    "nuvem": "Massa visível de vapor de água no céu.",
    "obeso": "Que tem excesso de gordura corporal.",
    "obvio": "Que é evidente, claro, manifesto.",
    "odiar": "Sentir ódio, aversão profunda.",
    "ontem": "No dia anterior ao de hoje.",
    "ordem": "Organização, arranjo; comando.",
    "orgao": "Parte de um ser vivo com função específica.",
    "otimo": "Muito bom, excelente.",
    "ousar": "Ter a coragem de fazer algo; atrever-se.",
    "outro": "Diferente, diverso; mais um.",
    "ouvir": "Perceber os sons pelo sentido da audição.",
    "pacto": "Acordo formal entre duas ou mais partes.",
    "pagar": "Dar dinheiro em troca de algo.",
    "pajem": "Menino que acompanha a noiva na cerimônia.",
    "papel": "Folha fina feita de celulose para escrever.",
    "parar": "Cessar um movimento ou ação.",
    "parte": "Porção de um todo; fragmento.",
    "pasmo": "Estado de grande espanto ou admiração.",
    "passo": "Movimento de um pé ao andar; etapa.",
    "patio": "Área aberta dentro ou ao lado de um edifício.",
    "pausa": "Interrupção de uma atividade; descanso.",
    "pegar": "Segurar, agarrar; apanhar.",
    "pente": "Utensílio para arrumar os cabelos.",
    "perda": "Ato de perder algo ou alguém.",
    "perto": "A pequena distância; próximo.",
    "pilar": "Coluna que sustenta uma construção.",
    "pingo": "Pequena gota de um líquido.",
    "pique": "Corrida rápida e curta; disposição.",
    "pista": "Caminho delimitado; indício.",
    "pizza": "Prato de origem italiana com massa e cobertura.",
    "plano": "Superfície sem elevações; projeto.",
    "pobre": "Que tem poucos recursos financeiros.",
    "poema": "Obra literária em versos.",
    "poeta": "Pessoa que escreve poemas.",
    "ponta": "Extremidade afiada de algo.",
    "ponto": "Sinal gráfico; lugar específico.",
    "porem": "Contudo, todavia, entretanto.",
    "porta": "Abertura para entrar e sair de um local.",
    "posse": "Ato de possuir algo; poder.",
    "posto": "Lugar, posição; local de abastecimento.",
    "prado": "Campo coberto de erva; campina.",
    "praia": "Faixa de areia junto ao mar, rio ou lago.",
    "prato": "Utensílio onde se serve a comida.",
    "prazo": "Período de tempo determinado.",
    "prece": "Oração, súplica a uma divindade.",
    "preço": "Valor monetário de algo.",
    "preso": "Que está privado de liberdade; detido.",
    "preto": "Cor escura como o carvão; negro.",
    "primo": "Filho do tio ou da tia.",
    "prosa": "Forma de escrita não metrificada, em parágrafos.",
    "prova": "Exame, teste; demonstração de algo.",
    "pular": "Saltar, elevar-se no ar.",
    "quase": "Por pouco; aproximadamente.",
    "queda": "Ato de cair; declínio.",
    "quero": "Forma do verbo 'querer' na 1ª pessoa do singular.",
    "quota": "Parte que cabe a cada um numa repartição; cota.",
    "raiva": "Sentimento de fúria; doença viral.",
    "ramo": "Divisão do tronco ou galho de uma árvore.",
    "rever": "Ver novamente; examinar com atenção.",
    "rezar": "Dirigir preces a uma divindade; orar.",
    "risco": "Traço feito com um instrumento; perigo.",
    "ritmo": "Sucessão regular de sons ou movimentos.",
    "rosto": "Parte anterior da cabeça humana; face.",
    "roubo": "Ato de subtrair algo de alguém; furto.",
    "sadio": "Que tem saúde; saudável.",
    "salvo": "Livre de perigo; exceto.",
    "santo": "Pessoa canonizada pela Igreja; sagrado.",
    "saude": "Estado de bom funcionamento do organismo.",
    "secar": "Tornar-se seco; enxugar.",
    "selva": "Floresta densa, especialmente em regiões tropicais.",
    "sendo": "Forma do gerúndio do verbo 'ser'.",
    "serie": "Conjunto de coisas em sequência; seriado.",
    "sexta": "O sexto dia da semana.",
    "sinal": "Gesto ou marca para comunicar algo.",
    "sobra": "Aquilo que resta; excesso.",
    "sobre": "Em cima de; a respeito de.",
    "socio": "Membro de uma sociedade ou clube.",
    "solar": "Relativo ao Sol; casa nobre.",
    "somar": "Efetuar a operação de adição.",
    "sonso": "Que se faz de desentendido; dissimulado.",
    "subir": "Mover-se para um lugar mais alto.",
    "sumir": "Desaparecer; ocultar-se.",
    "super": "Prefixo que indica superioridade; ótimo.",
    "tarde": "Período do dia entre o meio-dia e a noite.",
    "temer": "Ter medo de; recear.",
    "tendo": "Forma do gerúndio do verbo 'ter'.",
    "tenis": "Calçado esportivo; esporte de raquete.",
    "tenso": "Rígido, esticado; ansioso.",
    "terra": "O planeta que habitamos; solo.",
    "teste": "Prova para avaliar conhecimentos ou qualidades.",
    "texto": "Conjunto de palavras que formam um escrito.",
    "tocar": "Entrar em contato físico; executar música.",
    "total": "Que abrange a totalidade; soma.",
    "traje": "Conjunto de roupas; vestimenta.",
    "trato": "Acordo, pacto; modo de tratar.",
    "treta": "Confusão, briga, discussão.",
    "troca": "Ato de trocar; substituição.",
    "turba": "Multidão em desordem; bando.",
    "turma": "Grupo de alunos; galera.",
    "turvo": "Que não é transparente; opaco, embaçado.",
    "unico": "Que é só um; exclusivo.",
    "unido": "Que está junto, ligado.",
    "usual": "Que é de uso comum; habitual.",
    "vacuo": "Espaço que não contém matéria; vazio.",
    "vagar": "Andar sem destino; estar desocupado.",
    "vaivem": "Movimento de ir e vir.",
    "valer": "Ter determinado valor ou preço.",
    "valor": "Qualidade que torna algo apreciável; preço.",
    "vasto": "Muito grande em extensão; amplo.",
    "velho": "De idade avançada; antigo.",
    "venda": "Ato de vender; faixa para cobrir os olhos.",
    "venia": "Licença, permissão; saudação respeitosa.",
    "vento": "Ar em movimento.",
    "viajar": "Deslocar-se de um lugar para outro.",
    "video": "Gravação de imagens e som.",
    "vidro": "Material transparente e quebradiço.",
    "vigia": "Pessoa que guarda ou vigia algo.",
    "vilao": "Personagem mau em uma história.",
    "vinho": "Bebida alcoólica feita de uvas.",
    "virar": "Mudar de posição ou direção.",
    "visao": "Sentido da vista; ponto de vista.",
    "visto": "Selo em passaporte; que foi visto.",
    "vital": "Essencial para a vida; de grande importância.",
    "viver": "Estar vivo; ter vida.",
    "vulto": "Forma ou imagem pouco nítida; figura.",
    "zelar": "Cuidar com atenção e interesse."
};