// palavras.js

const LISTA_DE_PALAVRAS = [
    "sagaz", "negro", "amigo", "exito", "mexer", "termo", "nobre", "senso",
    "afeto", "plena", "etica", "sutil", "vigor", "fazer", "ideia", "poder",
    "moral", "honra", "justo", "muito", "anexo", "fosse", "sonho", "tange",
    "lapso", "expor", "haver", "dengo", "casal", "saber", "pesar", "graça",
    "certo", "criar", "impor", "falar", "pedir", "prole", "dever", "tempo",
    "corja", "feliz", "mundo", "verbo", "apice", "forte", "lugar", "chuva",
    "sorte", "genio", "bravo", "festa", "abrir", "achar", "ajuda", "andar",
    "antes", "apelo", "apoio", "arroz", "arvor", "assaz", "assim", "astro",
    "atomo", "atras", "atual", "audio", "autor", "avisar", "axial", "bahia",
    "banal", "banca", "banho", "barco", "bater", "beber", "beijo", "belo",
    "bolsa", "brasa", "breve", "brisa", "busca", "cabelo", "calma", "campo",
    "canil", "canto", "carro", "carta", "casto", "causa", "ceder", "chefe",
    "cheio", "choro", "chulo", "ciclo", "cinco", "cisma", "civil", "claro",
    "clima", "coeso", "coisa", "comer", "conta", "conto", "corpo", "correr",
    "costa", "crime", "crise", "cruel", "culto", "cunho", "curar", "curso",
    "custo", "dança", "dados", "digno", "dizer", "doce", "dogma", "drama",
    "duelo", "duzia", "ecoar", "enfim", "entao", "errar", "espir", "estar",
    "etapa", "exato", "facil", "falha", "falso", "farol", "farto", "fatal",
    "favor", "fauna", "feixe", "filho", "filme", "final", "fluir", "folga",
    "forma", "forno", "fraco", "frase", "freio", "futil", "ganho", "garfo",
    "gerar", "gesto", "glosa", "gosto", "grato", "grave", "grito", "grupo",
    "heroi", "hiato", "hobby", "homem", "hoste", "humor", "icone", "idolo",
    "igual", "impar", "imune", "indio", "inerte", "inicio", "istmo", "jante",
    "jarda", "jarro", "jovem", "jogar", "juizo", "julgar", "junto", "labor",
    "lagoa", "laico", "lapis", "largo", "laser", "laudo", "lazer", "legua",
    "leigo", "leito", "lento", "letra", "levar", "livro", "louco", "louro",
    "lousa", "lutar", "macio", "maior", "malha", "mamãe", "manga", "manha",
    "manto", "marco", "maria", "matiz", "meigo", "meio", "mente", "mesmo",
    "metro", "mimos", "moeda", "moita", "molde", "molho", "monte", "morte",
    "motor", "mover", "multa", "musgo", "nadar", "nasal", "nascer", "natal",
    "navio", "nicho", "ninfa", "nivel", "noite", "nosso", "nuvem", "obeso",
    "obvio", "odiar", "olhar", "ontem", "ordem", "orgao", "otimo", "ousar",
    "outro", "ouvir", "pacto", "pagar", "pajem", "papel", "parar", "parte",
    "pasmo", "passo", "patio", "pausa", "pegar", "pente", "perda", "perto",
    "pilar", "pingo", "pique", "pista", "pizza", "plano", "pobre", "poema",
    "poeta", "ponta", "ponto", "porem", "porta", "posse", "posto", "prado",
    "praia", "prato", "prazo", "prece", "preço", "preso", "preto", "primo",
    "prosa", "prova", "pular", "quase", "queda", "quero", "quota", "raiva",
    "ramo", "rever", "rezar", "risco", "ritmo", "rosto", "roubo", "sadio",
    "salvo", "santo", "saude", "secar", "selva", "sendo", "serie", "sexta",
    "sinal", "sobra", "sobre", "socio", "solar", "somar", "sonso", "subir",
    "sumir", "super", "tarde", "temer", "tendo", "tenis", "tenso", "terra",
    "teste", "texto", "tocar", "total", "traje", "trato", "treta", "troca",
    "turba", "turma", "turvo", "unico", "unido", "usual", "vacuo", "vagar",
    "vaivem", "valer", "valor", "vasto", "velho", "venda", "venia", "vento",
    "viajar", "video", "vidro", "vigia", "vilao", "vinho", "virar", "visao",
    "visto", "vital", "viver", "vulto", "zelar"
];